fix root key creation url
unkeyed/unkey pull request #1683
Opened 2024-05-26 21:50 UTC by Makisuo

## What does this PR do?

Fix of broken docs link

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [X] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

2024-05-26 21:50 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/unkeyed/unkey?pullRequest=1683) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/unkeyed/unkey?pullRequest=1683) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/unkeyed/unkey?pullRequest=1683) it.</sub>

2024-05-26 22:16 UTC, perkinsjr requested changes
https://app.unkey.com/settings/root-keys/new

Is the correct URL for root key creation.

2024-05-27 20:48 UTC, Makisuo commented
Huh seems to be working now, yesterday I got a 404.

2024-05-28 11:23 UTC, perkinsjr approved these changes

2024-05-28 11:23 UTC, merged