fix: margin fix for copy button
unkeyed/unkey pull request #1793
Opened 2024-06-24 13:15 UTC by MichaelUnkey

## What does this PR do?

Fixes # (issue)

*If there is not an issue for this, please create one first. This is used to tracking purposes and also helps use understand why this PR exists*

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?

- Test A
- Test B

## Checklist

### Required

- [ ] Filled out the "How to test" section in this PR
- [ ] Read [Contributing Guide](./CONTRIBUTING.md)
- [ ] Self-reviewed my own code
- [ ] Commented on my code in hard-to-understand areas
- [ ] Ran `pnpm build`
- [ ] Ran `pnpm fmt`
- [ ] Checked for warnings, there are none
- [ ] Removed all `console.logs`
- [ ] Merged the latest changes from main onto my branch with `git pull origin main`
- [ ] My changes don't cause any responsiveness issues

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Unkey Docs if changes were necessary

2024-06-24 13:31 UTC, guilhermerodz requested changes

2024-06-24 13:31 UTC, guilhermerodz commented on apps/dashboard/app/(app)/settings/root-keys/new/client.tsx
>              <div className="relative -top-8 right-[88px] flex items-start justify-between gap-4">
You can use `items-center` instead with `items-start`. And then remove the `mt-1.5` from the `CopyButton`

2024-07-02 06:12 UTC, guilhermerodz approved these changes

2024-07-02 12:02 UTC, perkinsjr approved these changes

2024-07-02 12:07 UTC, merged