fix: revalidate keys page
unkeyed/unkey pull request #1840
Opened 2024-07-01 20:05 UTC by MichaelUnkey

## What does this PR do?
eng-1080

Fixes # (issue)

*If there is not an issue for this, please create one first. This is used to tracking purposes and also helps use understand why this PR exists*

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?

Check to see if key is present after deletion. And no errors are found

## Checklist

### Required

- [x] Filled out the "How to test" section in this PR
- [x] Read [Contributing Guide](./CONTRIBUTING.md)
- [x] Self-reviewed my own code
- [x] Commented on my code in hard-to-understand areas
- [x] Ran `pnpm build`
- [x] Ran `pnpm fmt`
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Unkey Docs if changes were necessary

2024-07-02 15:09 UTC, chronark commented on apps/dashboard/app/(app)/keys/[keyAuthId]/new/page.tsx
> +  revalidate(`/keys/${props.params.keyAuthId}`);
this revalidates on page render, but it should revalidate when a mutation finishes
you need to call this in the mutation

2024-07-02 19:32 UTC, chronark requested changes

2024-07-02 19:32 UTC, chronark commented on apps/dashboard/app/(app)/keys/[keyAuthId]/[keyId]/settings/delete-key.tsx
> +  const searchParams = useSearchParams();
let's pass this as a prop, just like the apiKey please

2024-07-06 14:03 UTC, perkinsjr requested changes
this is a test

2024-07-06 16:22 UTC, chronark commented on apps/dashboard/app/(app)/apis/[apiId]/page.tsx
> -export const runtime = "edge";
why is this necessary?

2024-07-06 16:22 UTC, chronark commented on apps/dashboard/app/(app)/keys/[keyAuthId]/[keyId]/settings/delete-key.tsx
> +      revalidate("/apis");
why is this necesary?

2024-07-06 16:22 UTC, chronark commented on apps/dashboard/app/(app)/keys/[keyAuthId]/[keyId]/settings/delete-key.tsx
> +      revalidate(`/keys/${keyAuthId}`);
why is this necessary?

2024-07-06 16:22 UTC, chronark commented on apps/dashboard/app/(app)/keys/[keyAuthId]/keys.tsx
> +export const revalidate = true;
what does this do?

2024-07-06 16:32 UTC, perkinsjr commented
Absolutely :+1:

2024-07-08 18:07 UTC, chronark approved these changes
LGTM if you have verified by testing it in the UI

2024-07-08 18:08 UTC, chronark commented
fyi this is blocked cause you had a “test” change request @perkinsjr can you approve or revoke that

2024-07-08 18:08 UTC, perkinsjr approved these changes

2024-07-08 18:09 UTC, MichaelUnkey commented
I did test it. But I also did last time and then it was broken for James

2024-07-08 18:13 UTC, merged