chore: cloudflare cache expose cachebuster in constructor
unkeyed/unkey pull request #1853
Opened 2024-07-03 13:41 UTC by MichaelUnkey

## What does this PR do?
Eng-1079

Fixes # (issue)

*If there is not an issue for this, please create one first. This is used to tracking purposes and also helps use understand why this PR exists*

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Chore (refactoring code, technical debt, workflow improvements)
- [ ] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?

- Test A
- Test B

## Checklist

### Required

- [ ] Filled out the "How to test" section in this PR
- [ ] Read [Contributing Guide](./CONTRIBUTING.md)
- [ ] Self-reviewed my own code
- [ ] Commented on my code in hard-to-understand areas
- [ ] Ran `pnpm build`
- [ ] Ran `pnpm fmt`
- [ ] Checked for warnings, there are none
- [ ] Removed all `console.logs`
- [ ] Merged the latest changes from main onto my branch with `git pull origin main`
- [ ] My changes don't cause any responsiveness issues

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Unkey Docs if changes were necessary

2024-07-05 08:59 UTC, chronark requested changes
Please make the cacheBuster an optional string, fall back to `v1` and remove it from all the examples, except documentation

2024-07-09 13:18 UTC, MichaelUnkey commented
What part did I miss?

2024-07-09 13:21 UTC, chronark commented
`cacheBuster: string | "v1"`  is not optional
what you need to do is `cacheBuster?: string`
and then in the code you need to fall back to `"v1"`  if it’s undefined

2024-07-09 13:23 UTC, MichaelUnkey commented
got it

2024-07-09 13:47 UTC, MichaelUnkey commented
Should I add the cachebuster to all examples on this page of docs or just in cloudflare section? For example the quickstart at the top? [https://www.unkey.com/docs/libraries/ts/cache/overview#quickstart](https://www.unkey.com/docs/libraries/ts/cache/overview#quickstart)
I would guess no cause its optional but not 100% on this

2024-07-09 13:48 UTC, chronark commented
just in the section I linked
[https://www.unkey.com/docs/libraries/ts/cache/overview#cloudflare](https://www.unkey.com/docs/libraries/ts/cache/overview#cloudflare)

2024-07-09 14:50 UTC, chronark commented on packages/cache/src/stores/cloudflare.ts
> +   * Set for cachestore version
```suggestion
   * The version of the cache store schema. If changes occur on your cache schema, 
   * incrementing this value ensures the old cached schema is not utilized.
   * @default "v1"
```

2024-07-09 15:00 UTC, chronark commented
Here’s what I think needs to be included in the docs:
1. when do I need this
2. what does it do
3. Where is the value used

How about something along the lines of:
>As your data changes, it is important to keep backwards compatibility in mind. If your cached values are no longer backwards compatible, it can cause problems. For example when a value changes from optional to required. In these cases you should purge the entire cache by setting a new `cacheBuster`  value. The `cacheBuster`  is used as part of the cache key and changes ensure you are not reading old data anymore.

Defaults to `v1`  if omitted.

2024-07-09 15:16 UTC, MichaelUnkey commented
Sounds good to me. I need to learn to elaborate more .

2024-07-09 18:52 UTC, merged