fix(Authorization): Adjust margins and fix overflow on the x-axis
unkeyed/unkey pull request #1898
Opened 2024-07-11 20:30 UTC by mcstepp

## What does this PR do?

On Authorization > Permissions, when there is a super long permission name that creates an overflow on the X axis, the scroll no longer crashes into the sidebar. Overflow within the permission container is appropriately contained. Margins and padding are preserved for look and feel. 

Fixes #1895 

*If there is not an issue for this, please create one first. This is used to tracking purposes and also helps use understand why this PR exists*

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?

Manual test.
- Create a permission with a really long name (40+ characters, I used 54 to test)
- Navigate to `/authorization/permissions/[permissionId]`. 
- Observe overflow on the x-axis. 
- Result: Overflow within the permission container is appropriate contained without crashing into the sidebar. Margins and padding are preserved for look and feel. 

Loom: https://www.loom.com/share/fb5fa2b3d5bb4fae86180e195aa28961

## Checklist

### Required

- [x] Filled out the "How to test" section in this PR
- [x] Read [Contributing Guide](./CONTRIBUTING.md)
- [x] Self-reviewed my own code
- [x] Commented on my code in hard-to-understand areas
- [x] Ran `pnpm build`
- [x] Ran `pnpm fmt`
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues

### Appreciated

- [x] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Unkey Docs if changes were necessary

2024-07-11 20:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/unkeyed/unkey?pullRequest=1898) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/unkeyed/unkey?pullRequest=1898) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/unkeyed/unkey?pullRequest=1898) it.</sub>

2024-07-11 20:43 UTC, perkinsjr requested changes
Everything looks good. 

Except on the sidebar the button for user management now is pushed to the very bottom of the height of the container. You wouldn't notice this without more usage of the platform.

See this image

Before:
![image](https://github.com/user-attachments/assets/39ff0867-2955-496b-874a-605e4f7cbfcc)

After your changes:
![image](https://github.com/user-attachments/assets/22ff705d-a2f3-48d6-8a75-bd26bfc49e64)

2024-07-12 15:29 UTC, mcstepp commented
Resolved. Edited original PR with additional info and screenshots.

2024-07-12 15:45 UTC, perkinsjr approved these changes

2024-07-12 15:55 UTC, merged