glossary
unkeyed/unkey pull request #2085
Opened 2024-09-12 16:28 UTC by p6l-richard

## What does this PR do?

Fixes # (issue)

*If there is not an issue for this, please create one first. This is used to tracking purposes and also helps use understand why this PR exists*

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?

- Test A
- Test B

## Checklist

### Required

- [ ] Filled out the "How to test" section in this PR
- [ ] Read [Contributing Guide](./CONTRIBUTING.md)
- [ ] Self-reviewed my own code
- [ ] Commented on my code in hard-to-understand areas
- [ ] Ran `pnpm build`
- [ ] Ran `pnpm fmt`
- [ ] Checked for warnings, there are none
- [ ] Removed all `console.logs`
- [ ] Merged the latest changes from main onto my branch with `git pull origin main`
- [ ] My changes don't cause any responsiveness issues

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Unkey Docs if changes were necessary

2024-09-12 16:28 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/unkeyed/unkey?pullRequest=2085) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/unkeyed/unkey?pullRequest=2085) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/unkeyed/unkey?pullRequest=2085) it.</sub>

2024-10-23 09:28 UTC, chronark reviewed
![CleanShot 2024-10-23 at 11 27 49@2x](https://github.com/user-attachments/assets/cf1c5d77-0678-4c36-a9f7-70d60a5ee6e7)
sidebar still has placeholder names

___

![CleanShot 2024-10-23 at 11 28 29@2x](https://github.com/user-attachments/assets/1f09ca71-dba8-4105-a94d-40cde9b95c63)

are we keeping the mask icon here? looks a bit weird

2024-10-23 09:28 UTC, chronark commented on apps/www/app/glossary/[slug]/_faq.tsx
> +          ))}
yup, this needs a key

2024-10-23 09:28 UTC, chronark commented on apps/www/app/glossary/[slug]/_faq.tsx
why the _ prefix on the file name?
is that just to differentiate it from the nextjs named files?

2024-10-23 09:28 UTC, chronark commented on apps/www/app/glossary/[slug]/_takeaways.tsx
> +      )}
that seems like an issue

2024-10-23 09:28 UTC, chronark commented on apps/www/app/glossary/[slug]/page.tsx
> +  const term = allGlossaries.find((term) => term.slug === `${params.slug}`);
yes please

2024-10-23 09:28 UTC, chronark commented on apps/www/app/glossary/[slug]/page.tsx
> +  const term = allGlossaries.find((term) => term.slug === `${params.slug}`) as Glossary;
yes please

2024-10-23 09:28 UTC, chronark commented on apps/www/components/glossary/codeblock.tsx
what's the reason why we don't reuse the existing code block component?

2024-10-23 09:34 UTC, chronark requested changes

2024-10-23 09:34 UTC, chronark commented on apps/www/components/glossary/darkTheme.tsx
why do we need this?
we already have code blocks with syntax highlighting afaik

2024-10-23 09:34 UTC, chronark commented on apps/www/components/glossary/mdx-components.tsx
why don't we reuse the blog mdx components?

2024-10-23 09:34 UTC, chronark commented on apps/www/components/glossary/terms-navigation-desktop.tsx
> +            >
yes please

2024-10-23 15:47 UTC, p6l-richard commented on apps/www/components/glossary/mdx-components.tsx
We do actually. These components got copied over when I copied the templates, which have their custom react markdown implementation for the readmes:
https://github.com/p6l-richard/unkey/blob/main/apps/www/app/templates/%5Bslug%5D/page.tsx

removed this: https://github.com/unkeyed/unkey/commit/9144569ecc4238a18fb8317d8e4710d5fa71b9b3

2024-10-23 16:14 UTC, p6l-richard commented on apps/www/app/glossary/[slug]/_faq.tsx
it keeps adds sorting to the components.
NextJS magic below, components above

I can remove the underscores though to stay consistent with the other namings.

2024-10-23 16:18 UTC, p6l-richard commented on apps/www/components/glossary/search.tsx
> +
nah

2024-10-23 16:19 UTC, p6l-richard commented on apps/www/components/glossary/search.tsx
> +      )}
not needed

2024-10-23 16:19 UTC, p6l-richard commented on apps/www/components/glossary/terms-rolodex-desktop.tsx
> +  };
react compiler will eventually handle that stuff

2024-10-23 16:20 UTC, p6l-richard commented on apps/www/content/glossary/mime-types.mdx
> +reviewer: andreas
nah

2024-10-23 16:20 UTC, p6l-richard commented on apps/www/components/glossary/search.tsx
> +      />
fair suggestion, but not sure if this isn't added under the hood by cmd+k?

2024-10-23 16:21 UTC, p6l-richard commented on apps/www/components/glossary/terms-stepper-mobile.tsx
> +  );
fair

2024-10-23 16:22 UTC, p6l-richard commented on apps/www/components/glossary/terms-stepper-mobile.tsx
> +  const nextTerm = sortedTerms[(startIndex + 1) % sortedTerms.length];
not overcomplicate

2024-10-23 16:25 UTC, p6l-richard commented on apps/www/components/glossary/codeblock.tsx
We do actually. These components got copied over when I copied the templates, which have their custom react markdown implementation for the readmes:
https://github.com/p6l-richard/unkey/blob/main/apps/www/app/templates/%5Bslug%5D/page.tsx

removed this: https://github.com/unkeyed/unkey/commit/9144569ecc4238a18fb8317d8e4710d5fa71b9b3

2024-10-23 16:26 UTC, p6l-richard commented on apps/www/app/glossary/[slug]/_faq.tsx
removed prefix: https://github.com/unkeyed/unkey/pull/2085/commits/312075bafd61a7569780991494a36460c9ec7e3c

2024-10-23 16:32 UTC, p6l-richard commented on apps/www/components/ui/button.tsx
> +);
shadcn

2024-10-23 16:32 UTC, p6l-richard commented on apps/www/app/glossary/[slug]/takeaways.tsx
> +        <CardTitle className="text-2xl font-bold text-white">MIME Types: Key Takeaways</CardTitle>
good

2024-10-25 09:11 UTC, chronark approved these changes

2024-10-25 11:57 UTC, merged