fix: update references from twitter.com to x.com
unkeyed/unkey pull request #2199
Opened 2024-10-05 10:01 UTC by Vardhaman619

## What does this PR do?

This PR updates all references from `twitter.com` to `x.com` in the codebase.

Fixes #2198 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [X] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?

To verify the changes, please perform the following steps:
1. Clone the repository and checkout to this branch.
2. Search the codebase for any remaining instances of `twitter.com` to ensure all have been updated to `x.com`.
3. Run the application to verify that all links function correctly without errors.

## Checklist

### Required

- [X] Filled out the "How to test" section in this PR
- [X] Read [Contributing Guide](./CONTRIBUTING.md)
- [X] Self-reviewed my own code
- [X] Commented on my code in hard-to-understand areas
- [X] Ran `pnpm build`
- [X] Ran `pnpm fmt`
- [X] Checked for warnings, there are none
- [X] Removed all `console.logs`
- [X] Merged the latest changes from main onto my branch with `git pull origin main`
- [X] My changes don't cause any responsiveness issues

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Unkey Docs if changes were necessary

2024-10-05 10:42 UTC, chronark approved these changes

2024-10-05 10:43 UTC, chronark commented
Please resolve the merge conflict, /apps/engineering/mint.json should be deleted

2024-10-08 13:54 UTC, chronark commented
why do you delete files in apps/engineering?

2024-10-08 15:19 UTC, Vardhaman619 commented
@chronark I attempted to resolve the merge conflicts, but I seem to have made some unintended changes, particularly regarding the deletion of files in the /apps/engineering/ directory.

Could you please guide me on what steps I missed or clarify which files exactly should remain or be deleted? I will make the necessary corrections promptly.

2024-10-10 16:54 UTC, perkinsjr commented on apps/www/content/blog/how-unkey-treats-marketing.mdx
> +- X(Twitter) Guesser game show... Which was hilarious.
This shouldn't be changed.

2024-10-10 16:54 UTC, perkinsjr requested changes
See my comment

2024-10-11 06:25 UTC, Vardhaman619 commented on apps/www/content/blog/how-unkey-treats-marketing.mdx
> +- X(Twitter) Guesser game show... Which was hilarious.
ok

2024-10-23 07:05 UTC, Vardhaman619 commented
@perkinsjr Could you please take a look at this PR

2024-10-23 11:01 UTC, chronark commented
there are merge conflicts

2024-10-25 12:16 UTC, Vardhaman619 commented
@chronark / @perkinsjr Could you please take a look at this PR

2024-10-26 16:44 UTC, perkinsjr approved these changes

2024-10-29 13:41 UTC, merged