Logs page v2
unkeyed/unkey pull request #2701
Opened 2024-12-04 10:46 UTC by ogzhanolguncu

## What does this PR do?

Fixes # (issue)

*If there is not an issue for this, please create one first. This is used to tracking purposes and also helps use understand why this PR exists*

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?

- Test A
- Test B

## Checklist

### Required

- [ ] Filled out the "How to test" section in this PR
- [ ] Read [Contributing Guide](./CONTRIBUTING.md)
- [ ] Self-reviewed my own code
- [ ] Commented on my code in hard-to-understand areas
- [ ] Ran `pnpm build`
- [ ] Ran `pnpm fmt`
- [ ] Checked for warnings, there are none
- [ ] Removed all `console.logs`
- [ ] Merged the latest changes from main onto my branch with `git pull origin main`
- [ ] My changes don't cause any responsiveness issues

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Unkey Docs if changes were necessary

2024-12-04 15:34 UTC, chronark commented
![CleanShot 2024-12-04 at 16 34 15@2x](https://github.com/user-attachments/assets/1df904bf-bbc5-4907-8eef-c6a151e9241b)
meta field has weird corners, probably missing an overflow-hidden

2024-12-04 15:45 UTC, chronark requested changes
![CleanShot 2024-12-04 at 16 43 11@2x](https://github.com/user-attachments/assets/cefb02da-010c-4289-9291-0ce61e1beef5)
We should not parse the body into key-values, it loses the information that this was actually json, and while we always expect json, the user might mess up and send us something invalid.

I'm good with optimistically calling `JSON.stringify(JSON.parse(body), null, 2)` in a try catch to try and format it nicely but falling back to displaying the raw string

2024-12-04 15:45 UTC, chronark commented on apps/dashboard/app/(app)/logs/components/logs-table.tsx
> +        <div className="p-2 flex items-center">Message</div>
```suggestion
        <div className="p-2 flex items-center">Response Body</div>
```

2024-12-04 15:45 UTC, chronark commented on apps/dashboard/app/(app)/logs/components/logs-table.tsx
> +        <div className="p-2 flex items-center">Request</div>
```suggestion
        <div className="p-2 flex items-center">Path</div>
```

2024-12-04 15:57 UTC, ogzhanolguncu commented
> ![CleanShot 2024-12-04 at 16 43 11@2x](https://private-user-images.githubusercontent.com/18246773/392462978-cefb02da-010c-4289-9291-0ce61e1beef5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzMjgwNjMsIm5iZiI6MTczMzMyNzc2MywicGF0aCI6Ii8xODI0Njc3My8zOTI0NjI5NzgtY2VmYjAyZGEtMDEwYy00Mjg5LTkyOTEtMGNlNjFlMWJlZWY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA0VDE1NTYwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkODM0NWQ1MzM3MDMzMjliZmFlMDc1NzNjZjViMWNmOGI5YzFiZjE3ZmQ3YWUzMTM0NGU2YjI5ZDEyNDEwOTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.wz8I9VMdy3Ix07tNJ6DCNW_blJPZdXrg_qeBiyGyRvI)
> 
> We should not parse the body into key-values, and more importantly we should't uppercase their keys, it loses the information that this was actually json, and while we always expect json, the user might mess up and send us something invalid.
> 
> I'm good with optimistically calling `JSON.stringify(JSON.parse(body), null, 2)` in a try catch to try and format it nicely but falling back to displaying the raw string

I agree, yeah. Let's do this.

2024-12-04 15:58 UTC, ogzhanolguncu commented
> ![CleanShot 2024-12-04 at 16 33 25@2x](https://private-user-images.githubusercontent.com/18246773/392459312-16f301ae-550a-4311-8dea-ea10f747d727.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzMjgwNjIsIm5iZiI6MTczMzMyNzc2MiwicGF0aCI6Ii8xODI0Njc3My8zOTI0NTkzMTItMTZmMzAxYWUtNTUwYS00MzExLThkZWEtZWExMGY3NDdkNzI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA0VDE1NTYwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRmY2Y0NTk1OWQ0ZmQ0MjllNmRiNDVhNWVkY2YxOTAwNmExOGJhZGQyNTJjYWY1ZmFhZWY1Y2YyMmJkYThjZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.IGaW0wcv76Ij9Oofse29452ZpHUKIqMkSOpmbfIilW0) the separators are sometimes full width and sometimes not

Those are actually padded from left on purpose, but we can change that if we are not happy.

2024-12-04 16:26 UTC, chronark commented
> > ![CleanShot 2024-12-04 at 16 33 25@2x](https://private-user-images.githubusercontent.com/18246773/392459312-16f301ae-550a-4311-8dea-ea10f747d727.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzMjgwNjIsIm5iZiI6MTczMzMyNzc2MiwicGF0aCI6Ii8xODI0Njc3My8zOTI0NTkzMTItMTZmMzAxYWUtNTUwYS00MzExLThkZWEtZWExMGY3NDdkNzI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA0VDE1NTYwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRmY2Y0NTk1OWQ0ZmQ0MjllNmRiNDVhNWVkY2YxOTAwNmExOGJhZGQyNTJjYWY1ZmFhZWY1Y2YyMmJkYThjZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.IGaW0wcv76Ij9Oofse29452ZpHUKIqMkSOpmbfIilW0) the separators are sometimes full width and sometimes not
> 
> Those are actually padded from left on purpose, but we can change that if we are not happy.

It looks a bit off and unintentional, but maybe that's just me
It's a nitpick really and might change with vitors design anyways

let's keep it as is for now to move quickly

2024-12-05 11:35 UTC, chronark approved these changes

2024-12-05 11:39 UTC, merged