tests: Add unit tests for `@unkey/client`
unkeyed/unkey pull request #474
Opened 2023-11-13 16:33 UTC by KartikSoneji

## Type of change

- [ ] 🐛 Bug fix
- [ ] 🌟 New feature
- [ ] 🔨 Breaking change
- [x] 📖 Refactoring / dependency upgrade / documentation

## Description

Add unit tests for `@unkey/client`

### A picture tells a thousand words (if any)

### Before this PR
`<no tests>`

### After this PR

```console
> bun test:coverage
$ bun test --coverage
bun test v1.0.11 (f7f6233e)

test/client.test.ts:
✓ Unkey client > default config [0.34ms]
✓ Unkey client > respects config args [0.07ms]
✓ Unkey client > throws for invalid rootKey [0.24ms]
✓ Unkey client > retry.attempts works [15.09ms]
✓ Unkey client > calls succeed if fetch fails some retries [4.32ms]
✓ Unkey client > returns an error if fetch throws [11.00ms]
✓ Unkey client > retry.backoff is called as expected on each failure [6.77ms]
✓ snapshot api calls > client.keys > create [1.05ms]
✓ snapshot api calls > client.keys > update [0.49ms]
✓ snapshot api calls > client.keys > verify [1.59ms]
✓ snapshot api calls > client.keys > revoke [1.49ms]
✓ snapshot api calls > client.apis > client._internal > createRootKey [0.62ms]
✓ snapshot api calls > client.apis > client._internal > deleteRootKey [0.44ms]
✓ snapshot api calls > client.apis > update [0.38ms]
✓ snapshot api calls > client.apis > remove [0.42ms]
✓ snapshot api calls > client.apis > get [0.24ms]
✓ snapshot api calls > client.apis > listKeys [0.61ms]

test/mock-fetch.test.ts:

test/verify.test.ts:
✓ verifyKey() function > accepts plain string [0.30ms]
✓ verifyKey() function > accepts { key, apiId } [0.20ms]
---------------|---------|---------|-------------------
File           | % Funcs | % Lines | Uncovered Line #s
---------------|---------|---------|-------------------
All files      |   99.14 |  100.00 |
 src/client.ts |   96.55 |  100.00 |
 src/errors.ts |  100.00 |  100.00 |
 src/index.ts  |  100.00 |  100.00 |
 src/verify.ts |  100.00 |  100.00 |
---------------|---------|---------|-------------------

 19 pass
 0 fail
 81 expect() calls
Ran 19 tests across 3 files. [178.00ms]
```

2023-11-17 20:08 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/unkeyed/unkey?pullRequest=474) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/unkeyed/unkey?pullRequest=474) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/unkeyed/unkey?pullRequest=474) it.</sub>

2023-11-23 17:43 UTC, chronark requested changes

2023-11-23 17:51 UTC, KartikSoneji commented on packages/api/test/client.test.ts
> +    expect(client.rootKey).toBe(rootKey);
Fair point, I'll remove `rootKey`.
`baseUrl` is defined as public.
https://github.com/unkeyed/unkey/blob/44e5192a59d0f530e4d1c79458b914a579cc45df/packages/api/src/client.ts#L74

2023-11-23 17:51 UTC, KartikSoneji commented on packages/api/test/client.test.ts
> +    expect(mockFetch).toHaveBeenCalledTimes(4);
No it retries on failure.

2023-12-08 07:34 UTC, chronark approved these changes

2023-12-08 08:07 UTC, merged