feat:  Allow temporarily disabling a key
unkeyed/unkey pull request #767
Opened 2024-01-05 13:17 UTC by MichaelUnkey

## What does this PR do?
Eng-232

"enabled" column was added to the keys table. Web and api were updated to allow use of this boolean. 

Fixes # (issue)

*If there is not an issue for this, please create one first. This is used to tracking purposes and also helps use understand why this PR exists*

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] Enhancement (small improvements)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?

Test api to make sure all functions correctly 
Check web to make sure new feature works as intended
Check to make sure docs are updated correctly

- Test A
- Test B

## Checklist

### Required

- [x] Filled out the "How to test" section in this PR
- [x] Read [Contributing Guide](./CONTRIBUTING.md)
- [x] Self-reviewed my own code
- [x] Commented on my code in hard-to-understand areas
- [x] Ran `pnpm build`
- [x] Ran `pnpm fmt`
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues

### Appreciated
![Screenshot 2024-01-05 at 8 15 15 AM](https://github.com/unkeyed/unkey/assets/148160799/de97aa41-eff0-4a1e-8658-ff31629a2f37)
![Screenshot 2024-01-05 at 8 15 28 AM](https://github.com/unkeyed/unkey/assets/148160799/124e1959-196f-4d7a-82a1-0b8972b2b38f)
- [x] If a UI change was made: Added a screen recording or screenshots to this PR
- [x] Updated the Unkey Docs if changes were necessary

2024-01-05 13:46 UTC, perkinsjr approved these changes

2024-01-08 15:45 UTC, chronark requested changes

2024-01-08 15:45 UTC, chronark commented on apps/api/src/pkg/keys/service.ts
> +      code: "FORBIDDEN" | "RATE_LIMITED" | "USAGE_EXCEEDED" | "UNAUTHORIZED";
@MichaelUnkey let's go with `DISBABLED` :)

2024-01-08 16:27 UTC, MichaelUnkey commented on apps/api/src/pkg/keys/service.ts
> +      code: "FORBIDDEN" | "RATE_LIMITED" | "USAGE_EXCEEDED" | "UNAUTHORIZED";
Added as requested

2024-01-08 16:27 UTC, MichaelUnkey commented on apps/api/src/routes/v1_keys_updateKey.ts
> +          enabled: req.enabled === null ? undefined : req.enabled,
Added tests and made requested changes

2024-01-08 16:29 UTC, MichaelUnkey commented on apps/web/components/dashboard/api-key-table/index.tsx
> +            <CheckCircle2 />
changed

2024-01-08 16:30 UTC, MichaelUnkey commented on apps/web/components/dashboard/api-key-table/index.tsx
> +            <XCircle />
Changed

2024-01-10 17:04 UTC, chronark commented on internal/db/src/schema/keys.ts
> +    enabled: boolean("enabled").default(true).notNull(),
looks good to go

2024-01-10 17:04 UTC, chronark approved these changes

2024-01-10 17:10 UTC, merged