feat: Eng 374 convert newsletter server action to trpc
unkeyed/unkey pull request #778
Opened 2024-01-09 13:37 UTC by MichaelUnkey

## What does this PR do?

Changed newsletter email signup from Server Actions to tRPC.

Fixes # (issue)

*If there is not an issue for this, please create one first. This is used to tracking purposes and also helps use understand why this PR exists*

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] Enhancement (small improvements)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?

Make sure newsletter signup still functions as expected with resend. 

## Checklist

### Required

- [x] Filled out the "How to test" section in this PR
- [x] Read [Contributing Guide](./CONTRIBUTING.md)
- [x] Self-reviewed my own code
- [x] Commented on my code in hard-to-understand areas
- [x] Ran `pnpm build`
- [x] Ran `pnpm fmt`
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Unkey Docs if changes were necessary

2024-01-11 13:19 UTC, chronark requested changes

2024-01-11 13:19 UTC, chronark commented on apps/web/components/landing/newsletter.tsx
> +  function handleSubmit(event: any) {
Let's make this typesafe similar to here: https://github.com/unkeyed/unkey/blob/f6174806463e2e96d8120f3cf497de5588ec9987/apps/web/app/(authenticated)/(app)/app/settings/team/invite.tsx#L56

2024-01-11 13:19 UTC, chronark commented on apps/web/lib/trpc/routers/newsletter.ts
> +      if (!email) {
we don't need this check, by using a zod schema in the input function above, it is already checked

2024-01-11 13:19 UTC, chronark commented on apps/web/lib/trpc/routers/newsletter.ts
> +        email: z.string(),
they got a nice utility that does some validity checking for us
```suggestion
        email: z.string().email(),
```

2024-01-11 13:19 UTC, chronark commented on apps/web/lib/trpc/routers/newsletter.ts
> +        throw new TRPCError({
let's log the error here
```suggestion
        console.error(res.error)
        throw new TRPCError({
```

2024-01-12 19:41 UTC, MichaelUnkey commented
Issues with middleware moving back to server actions

2024-01-12 19:41 UTC, closed without merging