added warning when api with already existing name is created
unkeyed/unkey pull request #792
Opened 2024-01-11 17:07 UTC by dhawalpatil200

## What does this PR do?

Fixes # (issue)

*If there is not an issue for this, please create one first. This is used to tracking purposes and also helps use understand why this PR exists*

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?

- Test A
- Test B

## Checklist

### Required

- [ ] Filled out the "How to test" section in this PR
- [ ] Read [Contributing Guide](./CONTRIBUTING.md)
- [ ] Self-reviewed my own code
- [ ] Commented on my code in hard-to-understand areas
- [ ] Ran `pnpm build`
- [ ] Ran `pnpm fmt`
- [ ] Checked for warnings, there are none
- [ ] Removed all `console.logs`
- [ ] Merged the latest changes from main onto my branch with `git pull origin main`
- [ ] My changes don't cause any responsiveness issues

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Unkey Docs if changes were necessary

2024-01-11 17:07 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/unkeyed/unkey?pullRequest=792) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/unkeyed/unkey?pullRequest=792) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/unkeyed/unkey?pullRequest=792) it.</sub>

2024-01-12 10:28 UTC, chronark commented
This just displays a warning and proceeds to create the api anyways.

I'd prefer if there would be a warning displayed in this form before you hit submit
![CleanShot 2024-01-12 at 11 26 53@2x](https://github.com/unkeyed/unkey/assets/18246773/43c87551-62c6-4183-8cc6-97e5c47b1984)

You could conditionally display an alert using this:
```tsx
<Alert variant="alert">
  <AlertTitle>Warning</AlertTitle>
  <AlertDescription>
    An API with this name already exists, are you sure you want to create another one?
  </AlertDescription>
</Alert>
              ```

2024-01-16 13:04 UTC, chronark commented
@dhawalpatil200 please sign the CLA

2024-01-16 13:05 UTC, chronark requested changes

2024-01-16 13:05 UTC, chronark commented on apps/web/app/(authenticated)/(app)/app/apis/create-api-button.tsx
> +              {showAlert && (
please use `{showAlert ? (...) : null`

2024-01-17 15:55 UTC, dhawalpatil200 commented
> @dhawalpatil200 please sign the CLA

What is CLA?

2024-01-17 16:17 UTC, dhawalpatil200 commented
**Issue 1 :** 
 async function onSubmit(values: z.infer<typeof formSchema>) {
    if (checkForDuplicateApi(values.name, apis)) {
      setShowAlert(true);
      return;
    }

    create.mutate(values);
  }
  
  
  If you observe here , if the apis name is duplicate then it will never allow user to create the api with same name. This is because of **return;** statement
  
  But if I remove return statement then. It will directly create api and that warning will not be shown.
  
  
  **Issue 2 :** 
  
If the warning is displayed in dialog and then if we click on cancel button. And after when we again click on create New api button, then warning is displayed this is because showAlert is not set to false. 

I'm facing above issues. Could you guys help me with this ?

2024-01-17 16:36 UTC, perkinsjr commented
> If you observe here , if the apis name is duplicate then it will never allow user to create the api with same name. This is because of **return;** statement

Inside this PR you will see a bot named CLA Assistant, it will have an option to click here to sign.

2024-04-30 15:49 UTC, closed without merging